"""initial_schema

Revision ID: 0581b6d98905
Revises: 
Create Date: 2026-03-23 01:41:52.082925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0581b6d98905'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('peak_memory_mb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_connector_id'), 'ingestion_runs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('source_label', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('citation_url', sa.String(length=2048), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_connector_id'), 'raw_records', ['connector_id'], unique=False)
    op.create_index('ix_raw_records_connector_published', 'raw_records', ['connector_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_raw_records_fingerprint'), 'raw_records', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_raw_records_published_at'), 'raw_records', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_records_record_type'), 'raw_records', ['record_type'], unique=False)
    op.create_table('source_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_key', sa.String(length=128), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_record_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'connector_id', name='uq_checkpoint_scope_connector')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_name'), 'workflow_runs', ['workflow_name'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_workflow_run_id'), 'report_snapshots', ['workflow_run_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_record_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=False),
    sa.Column('entity_tags', sa.JSON(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_raw_record_id'), 'signals', ['raw_record_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_strength'), 'signals', ['strength'], unique=False)
    op.create_index('ix_signals_type_strength', 'signals', ['signal_type', 'strength'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_runs_status'), 'task_runs', ['status'], unique=False)
    op.create_index(op.f('ix_task_runs_task_name'), 'task_runs', ['task_name'], unique=False)
    op.create_index(op.f('ix_task_runs_workflow_run_id'), 'task_runs', ['workflow_run_id'], unique=False)
    op.create_index('ix_task_runs_workflow_status', 'task_runs', ['workflow_run_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_runs_workflow_status', table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_workflow_run_id'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_task_name'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_status'), table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_index('ix_signals_type_strength', table_name='signals')
    op.drop_index(op.f('ix_signals_strength'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_raw_record_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_report_snapshots_workflow_run_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_workflow_runs_workflow_name'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('source_checkpoints')
    op.drop_index(op.f('ix_raw_records_record_type'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_published_at'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_fingerprint'), table_name='raw_records')
    op.drop_index('ix_raw_records_connector_published', table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_connector_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_connector_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
